In [47]:
import os
import pickle

import implicit
import numpy as np
import pandas as pd
import scipy.sparse
from tqdm import tqdm

In [2]:
df = pickle.load(open("../../data/cleaned_data/user_anime_lists.pkl", "rb"))

## TODO remove this

In [3]:
extra = pickle.load(
    open("../../../anime_recommender/data/user_profiles/ExtraUserAnimeLists.pkl", "rb")
)
df = pd.concat(
    [
        df.loc[lambda x: ~x["username"].isin(extra.username)],
        extra[["username", "anime_id", "my_score"]],
    ],
    ignore_index=True,
)

# Normalization

In [4]:
average_rating = df["my_score"].mean()
user_bias = (
    pd.DataFrame(df.groupby("username")["my_score"].mean()).rename(
        {"my_score": "user_bias"}, axis=1
    )
    - average_rating
)
anime_bias = (
    pd.DataFrame(df.groupby("anime_id")["my_score"].mean()).rename(
        {"my_score": "anime_bias"}, axis=1
    )
    - average_rating
)

In [5]:
df = df.merge(anime_bias, on=["anime_id"]).merge(user_bias, on=["username"])
df["normalized_score"] = (
    df["my_score"] - df["anime_bias"] - df["user_bias"] - average_rating
)
df = df.dropna()

## Create a sparse matrix

In [6]:
user_ids = df[["username"]].drop_duplicates().reset_index(drop=True)
user_ids = user_ids.reset_index().rename({"index": "user_id"}, axis=1)

In [7]:
df = df.merge(user_ids, on="username")

In [14]:
# user-item matrix
R = scipy.sparse.coo_matrix((df["normalized_score"], (df["user_id"], df["anime_id"])))

In [18]:
for i, j, v in zip(R.row, R.col, R.data):
    print(i, j, v)
    break

0 21 0.6054736476506148


## Alternating least squares

In [53]:
# number of latent factors
K = 100

# user factors
X = np.random.default_rng().standard_normal((R.shape[0], K))

# item factors
Y = np.random.default_rng().standard_normal((K, R.shape[1]))

In [65]:
X[u, :]

array([ 0.84212542,  0.05647956,  1.38422928, -1.36568152,  1.23047597,
        0.39157219, -1.32036218,  0.74737695,  1.45640601, -0.59180446,
        0.04172253, -0.33977628,  0.63848984, -1.95739427,  0.38294226,
       -0.35605178,  0.33851752, -0.50882693,  1.36308425,  0.85092368,
        1.3924999 , -0.96214204, -0.57909811, -1.34670968, -1.26801485,
        1.49039446,  2.30033795,  0.83923011, -0.50188251, -1.10540208,
        0.3411895 , -1.78600506, -0.69228697, -0.8132054 , -0.2222082 ,
       -0.54112389, -0.83781031, -1.13588837, -0.79517271,  0.12945712,
        1.2039863 , -0.5435222 ,  0.85138593, -1.22453001,  1.45314017,
        1.63273581,  2.09341116, -0.41821475, -0.12447563,  2.31109379,
       -0.59378683,  0.53123804, -0.54914307,  0.3932507 ,  0.62264041,
        0.81384629, -0.04167501, -0.98871111, -1.21091292,  2.49631177,
       -1.71541655, -0.2511828 ,  0.45922761, -0.9633358 , -1.66269875,
       -2.23966565,  0.77250337,  0.06432058, -0.89757292,  0.66

In [66]:
for u, i, r in tqdm(zip(R.row, R.col, R.data)):
    print((X[u, :] @ Y[:, i]) ** 2)
    break

0it [00:00, ?it/s]

194.04008707580823


In [69]:
def training_loss(X, Y, R, λ):
    sse = 0
    N = 0
    for u, i, r in tqdm(zip(R.row, R.col, R.data)):
        sse += (r - X[u, :] @ Y[:, i]) ** 2
        N += 1
    return sse + λ * np.sum(X ** 2) + λ * np.sum(Y ** 2)

In [70]:
training_loss(X, Y, R, 0.1)

46358416it [02:14, 343953.73it/s]


4722489251.045748

In [48]:
user_item_mat[:, 0].asformat("coo")

<271680x1 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in COOrdinate format>

In [54]:
X.T @ user_item_mat[:, 1]

array([[ -66.00332253],
       [-483.78396434],
       [-596.32905136],
       [ 673.88067637],
       [ 281.20442432],
       [-366.30276219],
       [ 653.57415375],
       [-163.59993002],
       [-906.01998437],
       [-589.28197515]])

In [61]:
user_item_mat[:, 1].shape

(271680, 1)

In [60]:
X[:, 0].shape

(271680,)

In [58]:
X.T[0, :] + user_item_mat[:, 1]

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (271680,)  and requested shape (271680,1)

In [53]:
user_item_mat[:, 1].nonzero()

(array([     1,      2,      4, ..., 236466, 236467, 236468], dtype=int32),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int32))

In [44]:
X.T

array([[ 0.06562139,  1.42791229,  0.35396757, ..., -0.84945667,
         0.28283718,  0.2770499 ],
       [ 0.23053862,  0.22440642, -0.33240749, ...,  0.05164753,
         1.26772036, -0.66471765],
       [ 1.46876118,  0.37393615,  0.68481032, ...,  0.9879699 ,
        -0.10498704, -0.19720801],
       ...,
       [ 0.72083975,  0.44724505, -0.29310862, ...,  0.79588235,
         1.93882171,  0.19430441],
       [-0.98483782, -1.2906035 , -0.1195464 , ..., -1.32094051,
        -1.48430006,  0.1173306 ],
       [-0.2262312 , -0.72189462,  0.86276658, ..., -0.64379972,
        -1.34893883, -0.64031335]])

In [35]:
X.T @ X - user_item_mat[:, 0]

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (10,10)  and requested shape (271680,1)

In [ ]:
np.random.normal()

In [10]:
df

username  anime_id  my_score  anime_bias  user_bias  \
0              karthiga        21         9    0.960564  -0.059898   
1              karthiga        59         7    0.040203  -0.059898   
2              karthiga        74         7    0.316282  -0.059898   
3              karthiga       120         7    0.309858  -0.059898   
4              karthiga       178         7   -0.227339  -0.059898   
...                 ...       ...       ...         ...        ...   
46358411   temptemptemp     10040         6   -1.636717  -1.493860   
46358412  cinnamoroller     12963        10   -0.798860   2.506140   
46358413      inactiveX      5143         7   -0.652951  -0.493860   
46358414           omgm      5581         5   -1.857497  -2.493860   
46358415   CategoryKing     33669         1   -1.592345  -6.493860   

          normalized_score  user_id  
0                 0.605474        0  
1                -0.474165        0  
2                -0.750245        0  
3                -0.743821        0  
4                -0.206624        0  
...                    ...      ...  
46358411          1.636717   271675  
46358412          0.798860   271676  
46358413          0.652951   271677  
46358414          1.857497   271678  
46358415          1.592345   271679  

[46358416 rows x 7 columns]

In [9]:
os.environ["MKL_NUM_THREADS"] = "1"

In [20]:
model = implicit.als.AlternatingLeastSquares(factors=50)

In [21]:
model.fit(sparse_mat)

  0%|          | 0/15 [00:00<?, ?it/s]

In [22]:
recs = pd.DataFrame.from_records(
    model.recommend(19671, sparse_mat, 1000), columns=["anime_id", "score"]
)

In [23]:
seen_shows = df.loc[lambda x: x["username"] == "Fro116"]

In [24]:
recs.merge(seen_shows, on=["anime_id"])[["score", "my_score"]].corr()

score  my_score
score     1.000000  0.142057
my_score  0.142057  1.000000

In [25]:
anime = pd.read_csv("../../data/cleaned_data/anime.csv")

In [26]:
recs.loc[lambda x: ~x.anime_id.isin(seen_shows.anime_id)].merge(
    anime, on="anime_id"
).loc[lambda x: x["type"] == "TV"][:30]

anime_id     score  Unnamed: 0                             title  \
2      16498  1.125039        8123                Shingeki no Kyojin   
5      22319  1.000904        1235                       Tokyo Ghoul   
10     30276  0.909803        8863                     One Punch Man   
11     28223  0.853507       12967                      Death Parade   
12      7054  0.832874          11             Kaichou wa Maid-sama!   
13     22535  0.829360        9232        Kiseijuu: Sei no Kakuritsu   
15     27899  0.817018       12935                    Tokyo Ghoul √A   
16     14227  0.809003          13            Tonari no Kaibutsu-kun   
17      5114  0.793178        2555  Fullmetal Alchemist: Brotherhood   
18      6045  0.785958          16                    Kimi ni Todoke   
19     18153  0.774362        1471                 Kyoukai no Kanata   
20     22199  0.766068        5463                    Akame ga Kill!   
21      6746  0.761906        9555                        Durarara!!   
23      9919  0.734740        5437                    Ao no Exorcist   
24     22789  0.731038        3116                         Barakamon   
25     13601  0.721468        3226                       Psycho-Pass   
26     21995  0.716090        7446                      Ao Haru Ride   
27      4898  0.712657       13711                      Kuroshitsuji   
28      6702  0.702549         191                        Fairy Tail   
31     18897  0.695744        6806                           Nisekoi   
32      8074  0.692423        4825            Highschool of the Dead   
33       120  0.686635          32                     Fruits Basket   
34     28297  0.677928        6485                  Ore Monogatari!!   
35     30503  0.673027        6754                  Noragami Aragoto   
37     24833  0.657713         932                Ansatsu Kyoushitsu   
38        20  0.656313        4504                            Naruto   
39     14289  0.652766        1023                 Sukitte Ii na yo.   
41     28999  0.646640        3558                         Charlotte   
42      3588  0.631614        8453                        Soul Eater   
43     23755  0.628890         915                 Nanatsu no Taizai   

                                               genres type  \
2   Action, Military, Mystery, Super Power, Drama,...   TV   
5   Action, Mystery, Horror, Psychological, Supern...   TV   
10  Action, Sci-Fi, Comedy, Parody, Super Power, S...   TV   
11      Game, Mystery, Psychological, Drama, Thriller   TV   
12                    Comedy, Romance, School, Shoujo   TV   
13  Action, Sci-Fi, Horror, Psychological, Drama, ...   TV   
15  Action, Mystery, Horror, Psychological, Supern...   TV   
16     Slice of Life, Comedy, Romance, School, Shoujo   TV   
17  Action, Military, Adventure, Comedy, Drama, Ma...   TV   
18      Slice of Life, Drama, Romance, School, Shoujo   TV   
19               Slice of Life, Supernatural, Fantasy   TV   
20         Action, Adventure, Drama, Fantasy, Shounen   TV   
21                      Action, Mystery, Supernatural   TV   
23     Action, Demons, Fantasy, Shounen, Supernatural   TV   
24                              Comedy, Slice of Life   TV   
25              Action, Police, Psychological, Sci-Fi   TV   
26  Comedy, Drama, Romance, School, Shoujo, Slice ...   TV   
27  Action, Comedy, Demons, Fantasy, Historical, S...   TV   
28  Action, Adventure, Comedy, Magic, Fantasy, Sho...   TV   
31            Harem, Comedy, Romance, School, Shounen   TV   
32       Action, Horror, Supernatural, Ecchi, Shounen   TV   
33  Slice of Life, Comedy, Drama, Romance, Fantasy...   TV   
34                            Comedy, Romance, Shoujo   TV   
35   Action, Adventure, Comedy, Supernatural, Shounen   TV   
37                    Action, Comedy, School, Shounen   TV   
38  Action, Adventure, Comedy, Super Power, Martia...   TV   
39                     Drama, Romance, School, Shoujo   TV   
41                         Drama, S

In [19]:
recs.loc[lambda x: ~x.anime_id.isin(seen_shows.anime_id)].merge(
    anime, on="anime_id"
).loc[lambda x: x["type"] == "TV"][:30]

anime_id     score  Unnamed: 0                                  title  \
0      16498  0.897526        8123                     Shingeki no Kyojin   
1       5114  0.843040        2555       Fullmetal Alchemist: Brotherhood   
2       6746  0.833527        9555                             Durarara!!   
5       4898  0.790061       13711                           Kuroshitsuji   
6          1  0.762213        9132                           Cowboy Bebop   
7       7054  0.761894          11                  Kaichou wa Maid-sama!   
8      13601  0.759568        3226                            Psycho-Pass   
9         20  0.758924        4504                                 Naruto   
10      9919  0.751778        5437                         Ao no Exorcist   
11      3588  0.750829        8453                             Soul Eater   
12     30276  0.748766        8863                          One Punch Man   
13     22319  0.747155        1235                            Tokyo Ghoul   
14      6045  0.745603          16                         Kimi ni Todoke   
15      2251  0.734591        7238                               Baccano!   
16     14227  0.724538          13                 Tonari no Kaibutsu-kun   
17       205  0.698655        6463                       Samurai Champloo   
18     28223  0.695769       12967                           Death Parade   
19       269  0.678616          14                                 Bleach   
20      8074  0.676341        4825                 Highschool of the Dead   
22      3457  0.674743         848                         Vampire Knight   
23      6880  0.673509       12228                     Deadman Wonderland   
25      2025  0.664717         306  Darker than Black: Kuro no Keiyakusha   
26     22535  0.660454        9232             Kiseijuu: Sei no Kakuritsu   
27     14289  0.656725        1023                      Sukitte Ii na yo.   
28      6702  0.653898         191                             Fairy Tail   
29     11771  0.651365        3630                       Kuroko no Basket   
30      6707  0.649851         401                        Kuroshitsuji II   
32       120  0.645093          32                          Fruits Basket   
34     18153  0.630307        1471                      Kyoukai no Kanata   
35       877  0.629431         660                                   Nana   

                                               genres type  \
0   Action, Military, Mystery, Super Power, Drama,...   TV   
1   Action, Military, Adventure, Comedy, Drama, Ma...   TV   
2                       Action, Mystery, Supernatural   TV   
5   Action, Comedy, Demons, Fantasy, Historical, S...   TV   
6     Action, Adventure, Comedy, Drama, Sci-Fi, Space   TV   
7                     Comedy, Romance, School, Shoujo   TV   
8               Action, Police, Psychological, Sci-Fi   TV   
9   Action, Adventure, Comedy, Super Power, Martia...   TV   
10     Action, Demons, Fantasy, Shounen, Supernatural   TV   
11     Action, Fantasy, Comedy, Supernatural, Shounen   TV   
12  Action, Sci-Fi, Comedy, Parody, Super Power, S...   TV   
13  Action, Mystery, Horror, Psychological, Supern...   TV   
14      Slice of Life, Drama, Romance, School, Shoujo   TV   
15  Action, Mystery, Comedy, Historical, Supernatural   TV   
16     Slice of Life, Comedy, Romance, School, Shoujo   TV   
17  Action, Adventure, Comedy, Historical, Samurai...   TV   
18      Game, Mystery, Psychological, Drama, Thriller   TV   
19  Action, Adventure, Comedy, Super Power, Supern...   TV   
20       Action, Horror, Supernatural, Ecchi, Shounen   TV   
22  Drama, Mystery, Romance, Shoujo, Supernatural,...   TV   
23                    Action, Sci-Fi, Horror, Shounen   TV   
25               Action, Sci-Fi, Mystery, Super Power   TV   
26  Action, Sci-Fi, Horror, Psychological, Drama, ...   TV   
27                     Drama, Romance, School, Shoujo   TV   
28  Action, Adventure, Comedy, Magic, Fantasy, Sho...   TV   
29  

In [ ]:
anime

In [36]:
Y = np.random.rand(2000000, 10)

In [37]:
(Y.T @ Y).shape

(10, 10)

In [33]:
np.matmul?

Call signature:  np.matmul(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'matmul'>
File:            ~/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
Docstring:      
matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Matrix product of two arrays.

Parameters
----------
x1, x2 : array_like
    Input arrays, scalars not allowed.
out : ndarray, optional
    A location into which the result is stored. If provided, it must have
    a shape that matches the signature `(n,k),(k,m)->(n,m)`. If not
    provided or None, a freshly-allocated array is returned.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

    .. versionadded:: 1.16
       Now handles ufunc kwargs

Returns
-------
y : ndarray
    The matrix product of the inputs.
    This is a scalar only when both x1, x2 are 1-d vectors.

Raises
------
ValueError
    If the last dimension of `x1` is not the sam